version: '3.8'

services:

    database:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: autoparts_Root_Pass
            MYSQL_DATABASE: autoparts
            MYSQL_USER: autoparts_user
            MYSQL_PASSWORD: autoparts_Pass

    redis:
        image: redis:5-alpine
        command: redis-server --requirepass autoparts_redis_password
        ports:
            - "6379:6379"

#    database:
#        image: mcr.microsoft.com/mssql/server:2017-latest
#        ports:
#            - "1433:1433"
#        environment:
#            - SA_PASSWORD=autoparts_database_password
#            - ACCEPT_EULA=Y